In [1]:
import pandas as pd

In [ ]:
'''
- File Handling
- Data Wrangling
    - Data Cleaning
    - Data Transformation
    - Data Analysis
    - Feature Engineering
'''

In [4]:
# 1D -> Series -> pd.Series(1D list)
# 2D -> DataFrame -> pd.DataFrame(2D list)
# Pandas output shows both index and values of data.

In [3]:
numbers = pd.Series([1, 2, 3, 4, 5])
numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
data = [1, 2, 3, 4, 5]
for idx, val in enumerate(data):
    print(f'{idx}    {val}')
print(f'dtype: {type(val)}')

0    1
1    2
2    3
3    4
4    5
dtype: <class 'int'>

In [14]:
products = pd.DataFrame([
    ['Mobile', 'Samsung', 'Rs.60000'],
    ['Bottle', 'Invictus', 'Rs.1000'],
    ['Charger', 'Anker', 'Rs.5000'],
    ['Laptop', 'Asus', 'Rs.150000'],
    ['TV', 'LG', 'Rs.65000']
], columns=['Product Name', 'Brand', 'Price'],
    index=['A', 'B', 'C', 'D', 'E'])
products

  Product Name     Brand      Price
A       Mobile   Samsung   Rs.60000
B       Bottle  Invictus    Rs.1000
C      Charger     Anker    Rs.5000
D       Laptop      Asus  Rs.150000
E           TV        LG   Rs.65000

In [15]:
numbers.shape

(5,)

In [23]:
products.shape

(5, 3)

In [17]:
products.size

15

In [20]:
# nth dimension
products.ndim

2

In [28]:
numbers[1:4:2]

1    2
3    4
dtype: int64

In [35]:
# array[row, columns]
products['B':'D']
# products[1:4]

  Product Name     Brand      Price
B       Bottle  Invictus    Rs.1000
C      Charger     Anker    Rs.5000
D       Laptop      Asus  Rs.150000

## Loc and ILoc

In [ ]:
'''
- Loc -> Location -> Extract data using alphabetical index
- ILoc -> Integer Location -> Extract data using numeric index
'''

In [37]:
products.iloc[1:4, 1:]

      Brand      Price
B  Invictus    Rs.1000
C     Anker    Rs.5000
D      Asus  Rs.150000

In [38]:
products.loc['B':'D', 'Brand':]

      Brand      Price
B  Invictus    Rs.1000
C     Anker    Rs.5000
D      Asus  Rs.150000

In [49]:
products.iloc[
    [0, 1, 4],
    [0, 2]
]

  Product Name     Price
A       Mobile  Rs.60000
B       Bottle   Rs.1000
E           TV  Rs.65000

In [48]:
products.loc[
    ['A', 'B', 'E'],
    ['Product Name', 'Price']
]

  Product Name     Price
A       Mobile  Rs.60000
B       Bottle   Rs.1000
E           TV  Rs.65000

## Functions for File Handling

### Read Files

In [ ]:
'''
CSV File -> read_csv(file_name.csv)
Excel File -> read_excel(file_name.xlsx)
JSON File -> read_json(file_name.json)
SQL File -> read_sql(file_name.sql)
'''

### Create File

In [ ]:
'''
CSV File -> to_csv(file_name.csv, index=False)
Excel File -> to_excel(file_name.xlsx, index=False)
JSON File -> to_json(file_name.json, indent=4)
'''

## Read File

In [50]:
df = pd.read_csv('Dataset/Cardiovascular_Disease.csv')
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [60]:
# select top 5 records
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [54]:
# select bottom 5 records
df.tail()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [63]:
emp = pd.read_csv('Dataset/Employees.csv')
emp.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [64]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [ ]:
'''
- NaN -> Not a Number -> Numeric / Alphabetical
- NaT -> Not a Time -> Date / Time
'''